apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-guide
  labels:
    app.kubernetes.io/instance: route-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: route-guide
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: route-guide
    spec:
      containers:
        - name: route-guide
          image: "ghcr.io/aklivity/extras-route-guide-server:latest"
          ports:
            - containerPort: 50051
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 1
            periodSeconds: 3
          tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: route-guide
spec:
  selector:
    app.kubernetes.io/instance: route-guide
  ports:
    - name: http
      port: 50051
  type: ClusterIP
