openapi: 3.0.0
info:
  title: Todo App
  description: Manage a list of todo tasks
  version: 0.1.0
paths:
  /tasks:
    post:
      operationId: createTask
      summary: Create task
      tags:
        - Tasks API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
        required: true
      responses:
        '201':
          description: 201 Created
          headers:
            location:
              description: relative path to new task
              schema:
                type: string
        '412':
          description: 412 Precondition Failed
  /tasks/{id}:
    get:
      operationId: findTaskById
      summary: Find task by id
      tags:
        - Tasks API
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
    put:
      operationId: renameTask
      summary: Rename task
      tags:
        - Tasks API
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
        required: true
      responses:
        '204':
          description: 204 No Content
        '412':
          description: 412 Precondition Failed
    delete:
      operationId: deleteTask
      summary: Delete task
      tags:
        - Tasks API
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: 204 No Content
        '412':
          description: 412 Precondition Failed
components:
  schemas:
    task:
      type: object
      description: Task structure
      properties:
        name:
          type: string
          description: task name
