version: "3"
services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.16
    container_name: kafka
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
    ports:
      - 18081:18081
      - 18082:18082
      - 29092:29092
      - 19644:9644
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  console:
    image: docker.redpanda.com/redpandadata/console:v2.3.6
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: --topic-config "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 8080:8080

  redpanda-init:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        rpk topic create --brokers redpanda:29092 commands || exit 0
        rpk topic create --brokers redpanda:29092 replies
        rpk topic create --brokers redpanda:29092 transactions
        rpk topic create --brokers redpanda:29092 total-transactions
        rpk topic create --brokers redpanda:29092 average-transactions
        rpk topic create --brokers redpanda:29092 activities
        rpk topic create --brokers redpanda:29092 balances --topic-config cleanup.policy=compact
        rpk topic create --brokers redpanda:29092 balance-histories
        rpk topic create --brokers redpanda:29092 payment-requests --topic-config cleanup.policy=compact
        rpk topic create --brokers redpanda:29092 users --topic-config cleanup.policy=compact
    depends_on:
      redpanda:
        condition: service_healthy
    init: true

  dispatch-service:
    depends_on:
      redpanda-init:
        condition: service_completed_successfully
