ingress:
  enabled: true
  ingressClassName: nginx
  host: taxi.aklivity.io
  tls:
    enabled: true
    secretName: taxi-demo-tls
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
service:
  port: 80
