args: ["start", "-v", "-e", "-Pzilla.binding.kafka.client.connection.pool=false"]

extraEnv:
  - name: KAFKA_BOOTSTRAP_SERVER
    value: "kafka.taxi-demo.svc.cluster.local:9092"
  - name: KAFKA_USER
    value: "admin"
  - name: KAFKA_PASS
    value: "admin"
  - name: DISPATCH_SERVICE_HOST
    value: "dispatch-service.taxi-demo.svc.cluster.local"
  - name: DISPATCH_SERVICE_PORT
    value: "50051"
  - name: JAVA_OPTIONS
    value: "-Dzilla.binding.kafka.debug=true"

livenessProbePort: 7190
readinessProbePort: 7190

service:
  ports:
    - port: 7151
      name: grpc
    - port: 7190
      name: prometheus
