args: ["start", "-v", "-e", "-Pzilla.engine.worker.capacity=512", "-Pzilla.binding.kafka.client.connection.pool=false"]

extraEnv:
  - name: KAFKA_BOOTSTRAP_SERVER
    value: "kafka.taxi-demo.svc.cluster.local:9092"
  - name: KAFKA_USER
    value: "admin"
  - name: KAFKA_PASS
    value: "admin"
  - name: ZILLA_INCUBATOR_ENABLED
    value: "true"
  - name: JAVA_OPTIONS
    value: "-Dzilla.binding.kafka.debug=true"

livenessProbePort: 7190
readinessProbePort: 7190

service:
  ports:
    - port: 7114
      name: http
    - port: 7183
      name: mqtt
    - port: 7190
      name: prometheus
