openapi: 3.0.1
info:
  title: taxi_route.proto
  description: grpc-gateway definition for the taxi_route.proto service.
  version: 1.0.0
  license:
    name: Aklivity Community License
  contact:
    name: Aklivity Community
    url: https://www.aklivity.io/slack
externalDocs:
  description: Find out more about Zilla
  url: https://docs.aklivity.io/
servers:
  - url: localhost:8085
    description: Local app server
tags:
  - name: TaxiRoute
    description: TaxiRoute service defined in the protofile.
paths:
  /taxiroute.TaxiRoute/CreateTaxi:
    post:
      description: Create a taxi route
      tags:
        - TaxiRoute
      operationId: TaxiRoute_CreateTaxi
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/taxirouteRoute"
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/taxirouteRouteResponse"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
components:
  schemas:
    taxirouteRoute:
      type: object
      properties:
        key:
          type: string
        bbox:
          type: array
          items:
            type: number
            format: double
        distance:
          type: number
          format: double
        duration:
          type: number
          format: double
        coordinates:
          type: array
          items:
            type: array
            items:
              type: object
              properties: {}
    taxirouteRouteResponse:
      type: object
      properties:
        topic:
          type: string
    protobufAny:
      type: object
      properties:
        "@type":
          type: string
      additionalProperties:
        type: object
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: "#/components/schemas/protobufAny"
