openapi: 3.0.1
info:
  title: Taxi Hailing Demo
  version: version not set
  description: This demo showcases the MQTT protocol brokered by Zilla. It uses [Open Street Maps](https://www.openstreetmap.org/), [Open Route Service](https://openrouteservice.org/), and the [MQTT Simulator](https://github.com/DamascenoRafael/mqtt-simulator) to demonstrate a real-world taxi-hailing and location tracking service.
  contact:
    name: Aklivity Community
    url: https://www.aklivity.io/slack
servers:
  - url: public:80
    description: live server
  - url: localhost:8085
    description: local gateway server
  - url: localhost:7114
    description: local Zilla server
tags: 
  - name: Taxi
    description: Fetching Taxi info.
  - name: Bus
    description: Fetching Bus info.
paths:
  /taxi/locations:
    get: 
      operationId: getTaxiLocations
      description: Fetch all taxi locations.
      tags:
        - Taxi
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
  /taxi/locations/{id}:
    get: 
      operationId: getTaxiLocationById
      description: Fetch one taxi location by its ID.
      tags:
        - Taxi
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
  /bus/locations:
    get: 
      operationId: getBusLocations
      description: Fetch all bus locations.
      tags:
        - Bus
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
components:
  schemas:
    Location:
      required:
      - key
      properties:
        key:
          type: string
        icon:
          type: string
        coordinates:
          type: array
          items:
            type: integer
            format: int32

