services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.16
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:19092,external://0.0.0.0:${KAFKA_PORT}
      - --advertise-kafka-addr internal://redpanda:19092,external://${KAFKA_BOOTSTRAP_SERVER}
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
    ports:
      - 18081:18081
      - 18082:18082
      - 19644:9644
      - ${KAFKA_PORT}:${KAFKA_PORT}
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  console:
    image: docker.redpanda.com/redpandadata/console:v2.3.6
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:${KAFKA_PORT}"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 8080:8080

  redpanda-init:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        rpk topic create --brokers redpanda:19092 task-commands || exit 0;
        echo '## Creating the Kafka topics'
        rpk topic create --brokers redpanda:19092 task-commands --partitions 1
        rpk topic create --brokers redpanda:19092 task-replies --partitions 1
        rpk topic create --brokers redpanda:19092 task-snapshots --topic-config cleanup.policy=compact --partitions 1
        echo '## Created the Kafka topics'
    depends_on:
      redpanda:
        condition: service_healthy
    init: true
