name: Release Demo Artifacts

on:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tar all demos
        run: for i in */; do tar -zcvf "${i%/}.tar.gz" "$i"; done
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            startup.sh
            *.tar.gz
            LICENSE
