name: Build and Push route-guide-server image

on:
  push:
    branches:
      - "main"
    # paths:
    #   - 'extras-containers/route-guide-server/**/*'

jobs:
  buildx-push:
    uses: ./.github/workflows/example_test.yml
    with:
      image-name: extras-route-guide-server
      dockerfile-context: extras-containers/route-guide-server
