name: Build and Push taxi-service image

on:
  push:
    paths:
      - "extras-containers/taxi/grpc/service/**/*"

permissions:
  contents: read
  packages: write

jobs:
  docker-buildx-push:
    uses: ./.github/workflows/extras-container-build.yaml
    with:
      image-name: extras-taxi-service
      dockerfile-context: extras-containers/taxi/grpc/service
