name: Build and Push route-guide-server image

on:
  push:
    branches:
      - "main"
    # paths:
    #   - 'extras-containers/route-guide-server/**/*'

permissions:
  packages: write
  contents: read

jobs:
  docker-buildx-push:
    uses: ./.github/workflows/extras-container-build.yaml
    with:
      image-name: extras-route-guide-server
      dockerfile-context: extras-containers/route-guide-server
