name: Extra container builder

on:
  workflow_dispatch:
    inputs:
      image-name:
        required: true
        description: Name for the image
        type: string
      dockerfile-context:
        required: true
        description: Path to dockerfile
        type: string
      build-args:
        description: "build-time variables"
        required: false
        type: string
      
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-context:
        required: true
        type: string
      build-args:
        description: "build-time variables"
        required: false
        type: string


jobs:
  docker-buildx-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ inputs.dockerfile-context }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
            type=sha
          labels: |
            org.opencontainers.image.title=Zilla Demos ${{ inputs.image-name }}
            org.opencontainers.image.description=Supporting container for ${{ inputs.dockerfile-context }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/main/${{ inputs.dockerfile-context }}
          annotations: |
            manifest:org.opencontainers.image.title=Zilla Demos ${{ inputs.image-name }}
            manifest:org.opencontainers.image.description=Supporting container for ${{ inputs.dockerfile-context }}
            manifest:org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/main/${{ inputs.dockerfile-context }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.dockerfile-context }}
          build-args: ${{ inputs.build-args }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
