name: Build and Push sse-server image

on:
  push:
    branches:
      - '**'
    paths:
      - "extras-containers/sse-server/**/*"

permissions:
  contents: read
  packages: write

jobs:
  docker-buildx-push:
    uses: ./.github/workflows/extras-container-build.yaml
    with:
      image-name: extras-sse-server
      dockerfile-context: extras-containers/sse-server
