name: Check Streampay UI Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'streampay/app/**/*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: streampay/app/

      - name: Build image
        run: |
          cd streampay/app/
          docker build .
