name: Check Taxi Map UI Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'taxi/map-ui/**/*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: taxi/map-ui/

      - name: Build image
        run: |
          cd taxi/map-ui/
          docker build .
