name: Check Vortex UI Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'vortex/ui/**/*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: vortex/ui/

      - name: Build image
        run: |
          cd vortex/ui/
          docker build .
