yamlApplicationConfig:
  kafka:
    clusters:
      - name: zilla-demos
        bootstrapServers: pkc-p11xm.us-east-1.aws.confluent.cloud:9092
        readOnly: true
        properties:
          security.protocol: SASL_SSL
          sasl.mechanism: PLAIN
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
